service: serverless-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  urlInfo:
    handler: handler.urlInfo
    events:
      - http:
          path: urlinfo/1/{hostname_and_port}/{original_path_and_query_string}
          method: get
      - http:
          path: urlinfo/1
          method: get
