service: serverless-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hostInfo:
    handler: handler.hostInfo
    events:
      - http:
          path: urlinfo/1/{hostname_and_port}
          method: get
  queryInfo:
    handler: handler.queryInfo
    events:
      - http:
          path: urlinfo/1/{hostname_and_port}/{original_path_and_query_string}
          method: get
