service: serverless-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  urlinfo:
    handler: handler.urlinfo
    events:
      - http:
          path: urlinfo/1/{hostinfo}/{queryinfo}
          method: get
