service: serverless-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:

  urlcheck:
    handler: handler.urlcheck
    events:
      - http:
          method: get
          path: urlcheck
