service: serverless-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hostinfo:
    handler: handler.hostInfo
    events:
      - http:
          path: urlinfo/1/{hostname_and_port}
          method: get
